export * from './ficha.js';
export * from './importacao.js';
export * from './slug-legado.js';
export * from './lgpd.js';
export * from './anonimizacao.js';
export * from './confianca.js';
export * from './avaliacao.js';
export * from './recado.js';
export * from './whatsapp.js';
