/**
 * Fachada estável das Server Actions do admin.
 *
 * R11: as ações vivem por domínio em `./acoes/*`; as páginas continuam
 * importando deste arquivo para preservar o contrato público. Cada módulo
 * reexportado declara `use server` na própria origem; esta fachada não pode
 * declarar a diretiva, porque o compilador do Next exige exports locais de
 * funções async em arquivos marcados como Server Actions.
 */

export {
  acaoCriarConta,
  acaoEntrar,
  acaoSair,
  acaoEmpresa,
  acaoServicos,
  acaoProfissionais,
  acaoPagamentos,
  acaoPublicar,
  acaoMeiosAceitos,
  acaoJanela,
} from './acoes/onboarding';

export {
  acaoMarcarNoBalcao,
  acaoFotos,
  acaoUploadFoto,
  acaoRemoverFotoDaBarbearia,
  acaoCriarMembro,
  acaoTrocarPapel,
  acaoLigarMembro,
  acaoReemitirSenha,
  acaoTrocarMinhaSenha,
  acaoSalvarServico,
  acaoRegistrarSinal,
  acaoDevolverSinal,
  acaoConfiancaDoCliente,
  acaoLigarServico,
  acaoExigenciasDoServico,
  acaoSalvarProfissional,
  acaoLigarProfissional,
  acaoSalvarJornada,
  acaoSalvarRecursos,
  acaoEntrarNaFila,
  acaoAjustarFidelidade,
  acaoSalvarFidelidade,
  acaoAssumirRecado,
  acaoDevolverRecado,
  acaoResponderRecado,
  acaoEncerrarRecado,
  acaoDefinirVitrine,
  acaoRegistrarFoto,
  acaoPublicarFoto,
  acaoApagarFoto,
  acaoPerfilPublico,
  acaoContestarMarketplace,
  acaoLigarPrecoPorFaixa,
  acaoCriarFaixa,
  acaoApagarFaixa,
  acaoResolverLacuna,
  acaoMoverNaFila,
  acaoSentarDaFila,
} from './acoes/operacao';

export {
  acaoCriarExcecao,
  acaoRemoverExcecao,
  acaoMoverAgendamento,
  acaoAbrirCaixa,
  acaoMovimentarCaixa,
  acaoFecharCaixa,
  acaoAbrirComanda,
  acaoCancelarComanda,
  acaoRetomarCampanha,
  acaoTirarDaEspera,
  acaoAdicionarItem,
  acaoRemoverItem,
  acaoAjustarComanda,
  acaoFecharComanda,
  acaoCobrarComanda,
  acaoCancelarCobranca,
  acaoReceberFiado,
  acaoPoliticaDeSegundoFator,
  acaoComecarSegundoFator,
  acaoConfirmarSegundoFator,
  acaoDesligarSegundoFator,
  acaoVerificarSegundoFator,
  acaoSalvarRegraDeComissao,
  acaoRemoverRegraDeComissao,
  acaoConfiguracaoDeComissao,
  acaoAliquotaDoAdquirente,
  acaoFecharComissao,
  acaoAvisos,
} from './acoes/agenda-financeiro';

export {
  acaoPreferencias,
  acaoConvidar,
  acaoMeta,
  acaoAnalisarImportacao,
  acaoResolverConflitoImportacao,
  acaoAplicarImportacao,
  acaoReverterImportacao,
  acaoAdicionarSlug,
  acaoTrocarDePlano,
  acaoPermissoesDoPapel,
  acaoConsentimentoNoBalcao,
  acaoAbrirPedidoDeDados,
  acaoEncerrarPedidoDeDados,
  acaoAnonimizarCliente,
  acaoEncerrarSessao,
  acaoExpulsarSuporte,
  acaoPreferenciasDeAlerta,
  acaoSalvarPacote,
  acaoReembolsarPacote,
  acaoVenderPacote,
} from './acoes/clientes-conta';

export {
  acaoTratarAvaliacao,
  acaoContestarAvaliacao,
  acaoRetirarContestacao,
  acaoSalvarProduto,
  acaoMoverEstoque,
  acaoSalvarFicha,
  acaoSalvarPlano,
  acaoAssinar,
  acaoCancelarAssinatura,
  acaoCadastrarRecebedor,
  acaoSalvarSplit,
  acaoSalvarModeloDaAssinatura,
  acaoPagarFatura,
  acaoCancelarFatura,
  acaoAgendarCancelamento,
  acaoDesfazerCancelamento,
  acaoIncluirDependente,
  acaoRemoverDependente,
  acaoCriarContaDoFinanceiro,
  acaoQuitarContaDoFinanceiro,
  acaoCancelarContaDoFinanceiro,
  acaoCriarCategoriaDoFinanceiro,
  acaoCriarContaBancaria,
  acaoTransferirEntreContas,
  acaoDefinirLimiteDeFiado,
  acaoLancarSaldoInicialDeFiado,
  acaoAdiantarVale,
  acaoCancelarVale,
  acaoEstornarVenda,
  acaoTransferirPacote,
} from './acoes/produto';

export {
  acaoSalvarFiscal,
  acaoEmitirNota,
  acaoSalvarDocumentoDoTomador,
  acaoCriarCampanha,
  acaoEnviarCampanha,
  acaoSalvarAutomacao,
  acaoLigarAutomacao,
  acaoSalvarCadastroDoWhatsApp,
  acaoIrParaMeta,
  acaoConectarWhatsApp,
  acaoMandarMensagem,
  acaoConciliarWhatsApp,
  acaoSubmeterTemplate,
  acaoCancelarNota,
  acaoEscolherUnidade,
  acaoDefinirUnidadesDaConta,
  acaoTransferirEstoque,
  acaoAbrirUnidade,
  acaoDefinirUnidadeAtiva,
  acaoPerguntarAoAssistente,
  acaoPublicarNoPadrao,
  acaoDespublicarDoPadrao,
  acaoAdotarDoPadrao,
  acaoSalvarMetaDaRede,
  acaoCriarChave,
  acaoRevogarChave,
  acaoCadastrarWebhook,
  acaoDesligarWebhook,
} from './acoes/crescimento-plataforma';
